GET http://localhost:8080/api/organisations
### GET request to example server


###
POST http://localhost:8080/api/organisations
Content-Type: application/json

{
  "name": "Acme Corporation",
  "slug": "acme"
}

###

GET http://localhost:8080/api/organisations

###
POST http://localhost:8080/api/organisations
Content-Type: application/json

{
  "name": "",
  "slug": "INVALID SLUG"
}

###

POST http://localhost:8080/api/organisations
Content-Type: application/json

{
  "name": "Acme",
  "slug":
}